name: build

on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/build.yaml
      - Containerfile
      - requirements.txt
        
  workflow_dispatch:
    inputs:
      force_no_cache:
        description: 'Force build without cache'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@58cb9f5b71b1836d6f690c1e95effdeb9b98cb8a # v1.17.0
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      distribute: true
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      cache: ${{ github.event.inputs.force_no_cache != 'true' }}
      cache-mode: max
      file: "Containerfile"
      meta-images: ghcr.io/${{ github.repository }}/auth
      meta-tags: |
        type=ref,event=branch
        type=raw,value=latest,enable=${{ github.ref_name == 'master' }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
